### ISSUE TITLE
add artist or album to queue

### ISSUE THREAD

**Issue by moseylevy** [CommandFusion/Autonomic-MMS#12]
is there a command or can i add something to the js to add this ability?

i tried creating a button with 
mms.queueCurrentAlbum(list, listIndex, join)
(basically taking the add to queue for an individual title and changing it) 
but that did not work

**Comment by CF-Terence** [comment]
Yes, you can. Check out the following functions in the JS file:

playAlbumTrue: function(guid) { mms.sendCmd("PlayAlbum " + guid + " True"); },  
// Play selected Album. Will be added to the queue without interrupting playback.

playAlbumFalse: function(guid) { mms.sendCmd("PlayAlbum " + guid + " False"); },  
// Play selected Album. The queue will be cleared before the tracks are added

You would want to use the True functions. Will be similar with the queuing the Artist as well. Let me know whether it works because I haven't use these myself.

**Comment by moseylevy** [comment]
awesome thank you!
will check it out now.

**Comment by moseylevy** [comment]
it worked! 
i even copied and pasted those lines and tweaked the pasted set.
so now i have on command that gives me - play album now, 
and one command that gives me - add album to queue!

screenshot
http://d.pr/i/uodU

that was my first real JS editing ever...

**Comment by CF-Terence** [comment]
Great to hear that ... good work and continue to have a happy learning! :)
